#!/usr/bin/env Rscript

# Load required libraries
suppressPackageStartupMessages({
  library(Seurat)
})

# Get command line arguments
args <- commandArgs(trailingOnly = TRUE)

# Help function
show_help <- function() {
  cat("Seurat Object Inspector\n")
  cat("======================\n\n")
  cat("DESCRIPTION:\n")
  cat("  This script reads a Seurat RDS object and provides a comprehensive summary\n")
  cat("  of its structure and contents in a clean, formatted output.\n\n")
  cat("USAGE:\n")
  cat("  Rscript seurat_inspector.R <path_to_seurat_rds>\n")
  cat("  Rscript seurat_inspector.R -h | --help\n\n")
  cat("ARGUMENTS:\n")
  cat("  path_to_seurat_rds    Path to the RDS file containing a Seurat object\n\n")
  cat("OPTIONS:\n")
  cat("  -h, --help           Show this help message and exit\n\n")
  cat("OUTPUT INCLUDES:\n")
  cat("  • Basic object information (cells, features, class)\n")
  cat("  • Assay details (names, dimensions, available data slots)\n")
  cat("  • Dimensionality reductions (PCA, UMAP, tSNE, etc.)\n")
  cat("  • Metadata column summary with data types and ranges\n")
  cat("  • Clustering information (if clusters are present)\n")
  cat("  • Active cell identities and levels\n")
  cat("  • Additional object components (graphs, neighbors, commands)\n\n")
  cat("EXAMPLES:\n")
  cat("  # Inspect a Seurat object\n")
  cat("  Rscript seurat_inspector.R my_seurat_object.rds\n\n")
  cat("  # Show help\n")
  cat("  Rscript seurat_inspector.R -h\n\n")
  cat("REQUIREMENTS:\n")
  cat("  • R with Seurat package installed\n")
  cat("  • Valid Seurat object saved as RDS file\n\n")
  cat("AUTHOR:\n")
  cat("  Generated by Claude (Anthropic), Curated by Ryan Routsong (NIH)\n\n")
}

# Check for help flag or validate arguments
if (length(args) == 1 && (args[1] == "-h" || args[1] == "--help")) {
  show_help()
  quit(status = 0)
}

if (length(args) != 1) {
  cat("Error: Exactly one argument required.\n\n")
  show_help()
  quit(status = 1)
}

rds_path <- args[1]

# Check if file exists
if (!file.exists(rds_path)) {
  cat("Error: File", rds_path, "does not exist.\n")
  quit(status = 1)
}

# Read the Seurat object
cat("Reading Seurat object from:", rds_path, "\n")
cat(rep("=", 60), "\n", sep = "")

tryCatch({
  seurat_obj <- readRDS(rds_path)
}, error = function(e) {
  cat("Error reading RDS file:", e$message, "\n")
  quit(status = 1)
})

# Check if it's a Seurat object
if (!inherits(seurat_obj, "Seurat")) {
  cat("Error: The RDS file does not contain a Seurat object.\n")
  quit(status = 1)
}

cat("\n")

# Basic object information
cat("SEURAT OBJECT SUMMARY\n")
cat(rep("=", 60), "\n", sep = "")
cat("Class:", class(seurat_obj)[1], "\n")
cat("Number of cells:", ncol(seurat_obj), "\n")
cat("Number of features:", nrow(seurat_obj), "\n")
cat("\n")

# Assays information
cat("ASSAYS\n")
cat(rep("-", 30), "\n", sep = "")
assays <- names(seurat_obj@assays)
for (i in 1:length(assays)) {
  assay_name <- assays[i]
  assay <- seurat_obj@assays[[assay_name]]
  cat(sprintf("%d. %s\n", i, assay_name))
  cat(sprintf("   Features: %d\n", nrow(assay)))
  cat(sprintf("   Cells: %d\n", ncol(assay)))
  
  # Show available slots for each assay (compatible with Seurat v4 and v5)
  slots_available <- c()
  
  # Check for counts data
  if (inherits(assay, "Assay5")) {
    # Seurat v5 structure
    if (length(assay@layers) > 0) {
      layer_names <- names(assay@layers)
      if ("counts" %in% layer_names && length(assay@layers$counts) > 0) {
        slots_available <- c(slots_available, "counts")
      }
      if ("data" %in% layer_names && length(assay@layers$data) > 0) {
        slots_available <- c(slots_available, "data")
      }
      if ("scale.data" %in% layer_names && length(assay@layers$scale.data) > 0) {
        slots_available <- c(slots_available, "scale.data")
      }
    }
  } else {
    # Seurat v4 structure
    tryCatch({
      if (length(assay@counts) > 0) slots_available <- c(slots_available, "counts")
    }, error = function(e) {})
    
    tryCatch({
      if (length(assay@data) > 0) slots_available <- c(slots_available, "data")
    }, error = function(e) {})
    
    tryCatch({
      if (length(assay@scale.data) > 0) slots_available <- c(slots_available, "scale.data")
    }, error = function(e) {})
  }
  
  if (length(slots_available) > 0) {
    cat(sprintf("   Available data: %s\n", paste(slots_available, collapse = ", ")))
  }
  cat("\n")
}

# Default assay
cat("Default assay:", DefaultAssay(seurat_obj), "\n\n")

# Dimensionality reductions
cat("DIMENSIONALITY REDUCTIONS\n")
cat(rep("-", 30), "\n", sep = "")
reductions <- names(seurat_obj@reductions)
if (length(reductions) > 0) {
  for (reduction in reductions) {
    red_obj <- seurat_obj@reductions[[reduction]]
    cat(sprintf("• %s: %d dimensions\n", reduction, ncol(red_obj@cell.embeddings)))
  }
} else {
  cat("No dimensionality reductions found.\n")
}
cat("\n")

# Metadata columns
cat("METADATA COLUMNS\n")
cat(rep("-", 30), "\n", sep = "")
metadata <- seurat_obj@meta.data
cat("Number of metadata columns:", ncol(metadata), "\n")
cat("Metadata column names:\n")

for (i in 1:ncol(metadata)) {
  col_name <- colnames(metadata)[i]
  col_class <- class(metadata[[col_name]])[1]
  
  # Get summary info based on column type
  if (is.numeric(metadata[[col_name]])) {
    summary_info <- sprintf("(numeric: %.2f - %.2f)", 
                           min(metadata[[col_name]], na.rm = TRUE),
                           max(metadata[[col_name]], na.rm = TRUE))
  } else if (is.factor(metadata[[col_name]]) || is.character(metadata[[col_name]])) {
    n_unique <- length(unique(metadata[[col_name]]))
    summary_info <- sprintf("(%s: %d unique values)", col_class, n_unique)
  } else {
    summary_info <- sprintf("(%s)", col_class)
  }
  
  cat(sprintf("%2d. %-20s %s\n", i, col_name, summary_info))
}
cat("\n")

# Cluster information (if available)
if ("seurat_clusters" %in% colnames(metadata)) {
  cat("CLUSTERING INFORMATION\n")
  cat(rep("-", 30), "\n", sep = "")
  clusters <- table(metadata$seurat_clusters)
  cat("Number of clusters:", length(clusters), "\n")
  cat("Cells per cluster:\n")
  for (cluster in names(clusters)) {
    cat(sprintf("  Cluster %s: %d cells\n", cluster, clusters[cluster]))
  }
  cat("\n")
}

# Active identity
cat("ACTIVE IDENTITY\n")
cat(rep("-", 30), "\n", sep = "")
cat("Active identity class:", class(Idents(seurat_obj))[1], "\n")
if (is.factor(Idents(seurat_obj))) {
  cat("Identity levels:", length(levels(Idents(seurat_obj))), "\n")
  if (length(levels(Idents(seurat_obj))) <= 20) {
    cat("Levels:", paste(levels(Idents(seurat_obj)), collapse = ", "), "\n")
  }
}
cat("\n")

# Additional useful slots
cat("ADDITIONAL INFORMATION\n")
cat(rep("-", 30), "\n", sep = "")

# Commands
if (length(seurat_obj@commands) > 0) {
  cat("Commands run:", length(seurat_obj@commands), "\n")
  recent_commands <- tail(names(seurat_obj@commands), 5)
  cat("Recent commands:", paste(recent_commands, collapse = ", "), "\n")
}

# Graphs
if (length(seurat_obj@graphs) > 0) {
  cat("Graphs:", paste(names(seurat_obj@graphs), collapse = ", "), "\n")
}

# Neighbors
if (length(seurat_obj@neighbors) > 0) {
  cat("Neighbors:", paste(names(seurat_obj@neighbors), collapse = ", "), "\n")
}

cat("\n")
cat(rep("=", 60), "\n", sep = "")
cat("Summary complete!\n")